[package]
name = "collections_exercise_1"
version = "0.1.0"
authors = ["wkimeria"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
